format = """
$status \
$directory\
$nix_shell\
$git_branch\
$git_commit\
$git_state\
$git_status\
$dotnet\
$nodejs\
$cmd_duration\
$line_break\
$character"""
    
# Don't print a new line at the start of the prompt
add_newline = false

[nix_shell]
format = '[\[nix-shell\]]($style) '
symbol = ' '
style = 'bold green'

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "on [$hostname](bold yellow) "
trim_at = "."
disabled = false

[character]
success_symbol = " [➜ ](grey)"
error_symbol = " [❌ ](bold red)"

[cmd_duration]
min_time = 0
style = "#d65d0e"
format = "[$duration]($style) "

[directory]
truncation_length = 100
truncate_to_repo = true
style = " bold italic #458588"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = ""
style = "bold #fabd2f"
format = '[$symbol$branch≡]($style) '

[git_status]
style = "bold #ADDB67"
format = '([\[$untracked$conflicted$renamed$modified$deleted$staged$stashed$ahead_behind \]]($style)) '
modified = ' [~$count](yellow)'
untracked = " ?$count"
stashed =' [ $count](purple)'
deleted = ' [-$count](red)'
ahead = " [⇡$count](blue)"
staged = " [ $count](blue)"
diverged = " [⇡$ahead_count⇣$behind_count](bold #ec7213)"
behind = " [⇣$count](#ec7213)"
conflicted = " [❌$count](bold red)]"

[dotnet]
format = "[$symbol($version)]($style)"
version_format = "$major "
disabled = false

[status]
disabled = false
format = '[\[$status - $common_meaning\]](green)'

# [env_var]
# variable = "0"
